name: docker builds
on:
  push:
    paths:
    - 'Dockerfile.*'
    - 'baids/**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */8 * * *'
  watch:
    types: [started]

jobs:
  build-n-push:
    name: Build and push docker images
    runs-on: ubuntu-latest
    #if: ${{ ${{ github.event_name == 'started' && github.actor == github.event.repository.owner.login }} || github.event_name == 'push' }}
    if: ${{ ${{ github.event_name == 'started' && github.actor == 'rcmorano' }} || github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Registry
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: build-n-push
      env:
        CARDANO_NODE_BUILD_BRANCH: master
        DOCKER_REGISTRY: docker.io
        DOCKER_IMAGE_NAME: repsistance/cardano-node
        DOCKER_IMAGE_URI: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}
        DOCKER_SRC_TARGETS: "src src-build"
        DOCKER_FINAL_TARGETS: "guild-ops-ptn0-passive iohk-fftn-passive"
      run: |
        curl -sSL https://raw.githubusercontent.com/rcmorano/baids/master/baids | bash -s install
        ln -s $PWD/baids ~/.baids/functions.d/docker-cardano-node
        source ~/.baids/baids
        set -x
        export CARDANO_NODE_LONG_COMMIT=$(cardano-node-get-git-branch-head $CARDANO_NODE_BUILD_BRANCH)
        export CARDANO_NODE_COMMIT=${CARDANO_NODE_LONG_COMMIT:0:7}
        export CI_COMMIT_SHORT_SHA=${GITHUB_SHA:0:7}
        cardano-node-docker-build
        cardano-node-docker-push
